const siteDetails = [
  {
    mobile: `./assets/resident-mobile.gif`,
    desktop: `./assets/resident-desktop.gif`,
    visitLink: `https://residentapp.johnchimezie.online/`,
    repoLink: `https://github.com/nattyjojo/residentApp`,
    contributors: `John`,
    contributorsGithub: `https://github.com/nattyjojo?tab=repositories`,
    condition: `Visit Site`,
    name: "ResidentApp",
    discription: `ResidentApp is a dynamic resident app designed to add an element of surprise to your daily Housing management`,
  },
  {
    mobile: `./assets/mobile.png`,
    desktop: `./assets/desktop.png`,
    visitLink: `https://whimsical-melomakarona-344a50.netlify.app`,
    repoLink: `https://github.com/nattyjojo/becodeqanda`,
    contributors: "Prince",
    contributorsGithub: `https://github.com/prynskaf`,
    condition: `Visit Site`,
    name: "BeCodeQanda",
    discription:
      "BeCodeQanda is a web application that provides a platform for users to participate in quizzes. Users can register and join quizzes, create their own quizzes, and view existing quizzes. The app also includes a waiting page for users who have joined a quiz and are waiting for it to begin.",
  },
  {
    mobile: `./assets/calculator-mobile.png`,
    desktop: `./assets/calculator-desktop.png`,
    visitLink: `https://nattyjojo.github.io/6_Calculator-project/`,
    repoLink: `https://github.com/nattyjojo/6_Calculator-project`,
    contributors: `John`,
    contributorsGithub: `https://github.com/nattyjojo?tab=repositories`,
    condition: `Visit Site`,
    name: "calculator",
    discription: `User-friendly calculator app designed to simplify your mathematical tasks effortlessly. Whether you're a student, professional, or just need quick calculations on the go, QuickCalc is your go-to solution. With a clean and intuitive interface, it supports basic arithmetic, scientific functions, and more. `,
  },
  {
    mobile: `./assets/portfolioSite-mobile.png`,
    desktop: `./assets/portfolioSite-desktop.png`,
    visitLink: `https://nattyjojo.github.io/portfolio`,
    repoLink: `https://github.com/nattyjojo/portfolio`,
    contributors: `John`,
    contributorsGithub: `https://github.com/nattyjojo?tab=repositories`,
    condition: `Visit Site`,
    name: "portfolio",
    discription: `Welcome to my digital portfolio space! Here, creativity meets functionality to showcase a collection of my finest work and projects. Navigate through a curated display of my skills, experiences, and achievements. From web development to design, this portfolio is a visual journey that captures my passion for innovation. Join me on this exploration of projects that reflect my dedication to craftsmanship and problem-solving. Your next digital experience begins here.`,
  },
  {
    mobile: `./assets/collection-mobile.png`,
    desktop: `./assets/collection-desktop.png`,
    visitLink: `https://nattyjojo.github.io/The-Collection/`,
    repoLink: `https://github.com/nattyjojo/The-Collection`,
    contributors: `John`,
    contributorsGithub: `https://github.com/nattyjojo?tab=repositories`,
    condition: `Visit Site`,
    name: "collections",
    discription: `Embark on a journey through my personal homage to Dream League excellence! As a devoted fan, I've curated a collection that honors my favorite players—the heroes who redefine the virtual pitch. From skillful strikers to steadfast defenders, each player in my collection holds a special place in my heart. Join me in celebrating the passion, prowess, and pure magic of Dream League Soccer as I showcase the players who inspire my love for the game.`,
  },
];
export default siteDetails;
